DROP TABLE `option_quote`;
CREATE TABLE `option_quote` (
  `id` integer unsigned PRIMARY KEY AUTO_INCREMENT,
  `xday` integer DEFAULT NULL,
  `xmonth` integer DEFAULT NULL,
  `xyear` varchar(4) DEFAULT NULL,
  `ask` double DEFAULT NULL,
  `ask_time` varchar(16) DEFAULT NULL,
  `asksz` bigint(20) DEFAULT NULL,
  `basis` double DEFAULT NULL,
  `bid` double DEFAULT NULL,
  `bid_time` varchar(16) DEFAULT NULL,
  `bidsz` bigint(20) DEFAULT NULL,
  `chg` double DEFAULT NULL,
  `chg_sign` char(1) DEFAULT NULL,
  `chg_t` double DEFAULT NULL,
  `cl` double DEFAULT NULL,
  `contract_size` bigint(20) DEFAULT NULL,
  `date` TIMESTAMP NULL,
  `datetime` TIMESTAMP NULL,
  `days_to_expiration` bigint(20) DEFAULT NULL,
  `exch` varchar(32) DEFAULT NULL,
  `exch_desc` varchar(32) DEFAULT NULL,
  `hi` double DEFAULT NULL,
  `idelta` double DEFAULT NULL,
  `igamma` double DEFAULT NULL,
  `imp_volatility` double DEFAULT NULL,
  `incr_vl` integer DEFAULT NULL,
  `irho` double DEFAULT NULL,
  `issue_desc` varchar(255) DEFAULT NULL,
  `itheta` double DEFAULT NULL,
  `ivega` double DEFAULT NULL,
  `last` double DEFAULT NULL,
  `lo` double DEFAULT NULL,
  `op_delivery` varchar(16) DEFAULT NULL,
  `op_flag` integer DEFAULT NULL,
  `op_style` varchar(16) DEFAULT NULL,
  `op_subclass` integer DEFAULT NULL,
  `openinterest` integer DEFAULT NULL,
  `opn` double DEFAULT NULL,
  `opt_val` double DEFAULT NULL,
  `pchg` varchar(16) DEFAULT NULL,
  `pchg_sign` varchar(16) DEFAULT NULL,
  `pcls` double DEFAULT NULL,
  `phi` double DEFAULT NULL,
  `plo` double DEFAULT NULL,
  `popn` varchar(16) DEFAULT NULL,
  `pr_date` TIMESTAMP NULL,
  `pr_openinterest` integer DEFAULT NULL,
  `prchag` varchar(16) DEFAULT NULL,
  `prchg` double DEFAULT NULL,
  `prem_mult` bigint(20) DEFAULT NULL,
  `put_call` varchar(16) DEFAULT NULL,
  `pvol` bigint(20) DEFAULT NULL,
  `qcond` bigint(20) DEFAULT NULL,
  `rootsymbol` varchar(16) DEFAULT NULL,
  `secclass` varchar(16) DEFAULT NULL,
  `sesn` varchar(16) DEFAULT NULL,
  `strikeprice` double DEFAULT NULL,
  `symbol` varchar(32) DEFAULT NULL,
  `tcond` varchar(16) DEFAULT NULL,
  `timestamp` TIMESTAMP NULL,
  `tr_num` bigint(20) DEFAULT NULL,
  `tradetick` varchar(32) DEFAULT NULL,
  `trend` varchar(16) DEFAULT NULL,
  `under_cusip` varchar(16) DEFAULT NULL,
  `undersymbol` varchar(16) DEFAULT NULL,
  `vl` bigint(20) DEFAULT NULL,
  `vwap` double DEFAULT NULL,
  `wk52hi` double DEFAULT NULL,
  `wk52hidate` TIMESTAMP NULL,
  `wk52lo` double DEFAULT NULL,
  `wk52lodate` TIMESTAMP NULL,
  `xdate` TIMESTAMP NULL,
  `persistence_version` INTEGER, 
  `created` TIMESTAMP DEFAULT 0,
  `last_update` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

ALTER TABLE option_quote ADD COLUMN `stock_quote_id` integer DEFAULT NULL;